### PR TITLE
config file support

### PR DESCRIPTION
**Pull request by zoey-ada**
Add config file path extension setting.
Add include paths extension setting.

### CODE REVIEW

**Comment by notskm** [comment]
Hey, I can't seem to access the issue tracker on your repo, but I see you've removed my name from the license in your fork. You may not alter the license. You may sublicense the project, but the original notice must be maintained, as stated in the license file. By removing my name and adding yours, you are claiming to have made something you did not.

This may be a helpful source: https://softwareengineering.stackexchange.com/questions/386582/altering-author-names-in-mit-license

**Comment by zoey-ada** [comment]
My bad. I will fix that. Thanks for pointing it out. 👍🏻

**Comment by zoey-ada** [comment]
Fixed, or un-broken I guess.

That is some nifty info in that link. I'll have to hold on to it. I'm sure there are lots of others who could benefit from it.

Sorry again, and have a good one!

**Comment by notskm** [comment]
It's no big deal, thanks for fixing! I figured it was a simple honest mistake.

**Comment by danielbisar** [comment]
Will this ever be merged? This feature request is a good one and just saw this topic since otherwise I would create a PR as well.

**Comment by danielbisar** [comment]
Not sure if this project is dead... but since i did not receive any answer, if someone else is having the problem, there is and option to do the same with vscode cpptools extension. See my question and the responses on their repo:

https://github.com/microsoft/vscode-cpptools/issues/9981

**Pull request closed without merging**
